const handicaps = {
  HandsTied: {
    name: 'Hands tied behind the back',
    intelligence: 0,
    strength: -10,
    speed: -20,
    durability: 0,
    power: 0,
    combat: 0,
  },
  Hangover: {
    name: 'Hangover',
    intelligence: -15,
    strength: 0,
    speed: 0,
    durability: -10,
    power: 0,
    combat: 0,
  },
  LeadenShoes: {
    name: 'Leaden shoes',
    intelligence: 0,
    strength: 0,
    speed: -25,
    durability: -10,
    power: 0,
    combat: 0,
  },
  SadSong: {
    name: 'All by myself in your head',
    intelligence: 0,
    strength: -5,
    speed: -5,
    durability: -5,
    power: 0,
    combat: -10,
  },
  Jarjarbinks: {
    name: 'Jar Jar Binks by your side',
    intelligence: 0,
    strength: 0,
    speed: -10,
    durability: -5,
    power: 0,
    combat: -5,
  },
  Flu: {
    name: 'Flu',
    intelligence: 0,
    strength: -15,
    speed: -10,
    durability: -5,
    power: 0,
    combat: 0,
  },
  Weightlessness: {
    name: 'Weightlessness',
    intelligence: 0,
    strength: -25,
    speed: 0,
    durability: 0,
    power: -10,
    combat: 0,
  },
  Pepper: {
    name: 'Pepper in your nose',
    intelligence: -5,
    strength: 0,
    speed: 0,
    durability: -10,
    power: -5,
    combat: 0,
  },
  Blindfolden: {
    name: 'Blindfolden',
    intelligence: 0,
    strength: 0,
    speed: -15,
    durability: 0,
    power: -10,
    combat: 0,
  },
  Corset: {
    name: 'Lace-up corset',
    intelligence: 0,
    strength: -5,
    speed: -5,
    durability: -15,
    power: -5,
    combat: 0,
  },
  Float: {
    name: 'Display : float',
    intelligence: 0,
    strength: -15,
    speed: 0,
    durability: -5,
    power: 0,
    combat: -5,
  },
  Tartiflette: {
    name: 'Tartiflette',
    intelligence: 0,
    strength: -5,
    speed: -15,
    durability: -20,
    power: -5,
    combat: 0,
  },
  Nobody: {
    name: 'Nobody is nowhere',
    intelligence: -15,
    strength: 0,
    speed: -5,
    durability: 0,
    power: 0,
    combat: -10,
  },
  Agoraphobia: {
    name: 'Agoraphobia',
    intelligence: 0,
    strength: -5,
    speed: -15,
    durability: 0,
    power: -5,
    combat: -10,
  },
  InternetExplorer: {
    name: 'Internet Explorer',
    intelligence: -10,
    strength: -25,
    speed: 0,
    durability: -10,
    power: -10,
    combat: 0,
  },
  Banana: {
    name: 'Banana peel',
    intelligence: 0,
    strength: -5,
    speed: -10,
    durability: 0,
    power: -10,
    combat: 0,
  },
};
const weapons = {
  Excalibur: {
    name: 'Excalibur',
    intelligence: 0,
    strength: 15,
    speed: 0,
    durability: 0,
    power: 10,
    combat: 10,
  },
  Cloak: {
    name: 'Invisibility cloak',
    intelligence: 5,
    strength: 0,
    speed: 15,
    durability: 5,
    power: 0,
    combat: 0,
  },
  RedPill: {
    name: 'The red pill',
    intelligence: 25,
    strength: 0,
    speed: 0,
    durability: 0,
    power: 0,
    combat: 10,
  },
  Potion: {
    name: 'Panoramix potion',
    intelligence: 0,
    strength: 25,
    speed: 15,
    durability: 0,
    power: 25,
    combat: 0,
  },
  Dynamite: {
    name: 'Dynamite sticks',
    intelligence: 0,
    strength: 5,
    speed: 0,
    durability: 0,
    power: 20,
    combat: 10,
  },
  Sling: {
    name: 'Leather Sling',
    intelligence: 0,
    strength: 5,
    speed: 5,
    durability: 0,
    power: 0,
    combat: 5,
  },
  Mushroom: {
    name: 'Pink dotted mushroom',
    intelligence: 25,
    strength: 0,
    speed: 25,
    durability: 10,
    power: 0,
    combat: 25,
  },
  BlueShell: {
    name: 'Blue shell',
    intelligence: 0,
    strength: 15,
    speed: 0,
    durability: 0,
    power: 10,
    combat: 0,
  },
  Plunger: {
    name: 'Toilet plunger',
    intelligence: 0,
    strength: 10,
    speed: 0,
    durability: 0,
    power: 5,
    combat: 0,
  },
  VoodooDoll: {
    name: 'Voodoo doll',
    intelligence: 5,
    strength: 10,
    speed: 5,
    durability: 0,
    power: 10,
    combat: 0,
  },
  Tank: {
    name: 'Tank',
    intelligence: 0,
    strength: 25,
    speed: 0,
    durability: 15,
    power: 15,
    combat: 0,
  },
  Delorean: {
    name: 'The Delorean',
    intelligence: 0,
    strength: 0,
    speed: 25,
    durability: 10,
    power: 0,
    combat: 0,
  },
  Aegis: {
    name: 'Aegis',
    intelligence: 0,
    strength: 0,
    speed: 0,
    durability: 25,
    power: 0,
    combat: 5,
  },
  Tornado: {
    name: 'Tornado',
    intelligence: 0,
    strength: 0,
    speed: 25,
    durability: 20,
    power: 0,
    combat: 10,
  },
  Hotdog: {
    name: 'Screaming hotdog',
    intelligence: 0,
    strength: 10,
    speed: 0,
    durability: 0,
    power: 10,
    combat: 0,
  },
  Everybody: {
    name: 'Everybody is everywhere',
    intelligence: 15,
    strength: 0,
    speed: 5,
    durability: 0,
    power: 0,
    combat: 10,
  },
};

// ***Fields/Conditions***
const fields = {
  IceArena: {
    name: 'In an ice arena, in -15°C',
    intelligence: 10,
    strength: '',
    speed: 80,
    durability: '',
    power: '',
    combat: '',
  },
  Volcano: {
    name: 'In the crater of a prehistoric volcano',
    intelligence: '',
    strength: '',
    speed: '',
    durability: '',
    power: '',
    combat: '',
  },
  Beach: {
    name: 'On the beach, during a hurricane',
    intelligence: '',
    strength: '',
    speed: '',
    durability: '',
    power: '',
    combat: '',
  },
  Swamp: {
    name: 'In a sploch sploch swamp',
    intelligence: '',
    strength: '',
    speed: '',
    durability: '',
    power: '',
    combat: '',
  },
  Trampoline: {
    name: 'In a trampoline full of kids',
    intelligence: '',
    strength: '',
    speed: '',
    durability: '',
    power: '',
    combat: '',
  },
  Mars: {
    name: 'In the middle of the Oceanus Borealis on Mars',
    intelligence: '',
    strength: '',
    speed: '',
    durability: '',
    power: '',
    combat: '',
  },
};

export { handicaps, weapons, fields };
