/* eslint-disable prettier/prettier */
const handicaps = [
  {
    id: 0,
    name: 'No handicap',
    intelligence: 0,
    strength: 0,
    speed: 0,
    durability: 0,
    power: 0,
    combat: 0,
  },
  {
    id: 2,
    name: 'Hands tied behind the back',
    intelligence: 0,
    strength: -10,
    speed: -20,
    durability: 0,
    power: 0,
    combat: 0,
  },
  {
    id: 3,
    name: 'Hangover',
    intelligence: -15,
    strength: 0,
    speed: 0,
    durability: -10,
    power: 0,
    combat: 0,
  },
  {
    id: 4,
    name: 'Leaden shoes',
    intelligence: 0,
    strength: 0,
    speed: -25,
    durability: -10,
    power: 0,
    combat: 0,
  },
  {
    id: 5,
    name: 'All by myself in your head',
    intelligence: 0,
    strength: -5,
    speed: -5,
    durability: -5,
    power: 0,
    combat: -10,
  },
  {
    id: 6,
    name: 'Jar Jar Binks by your side',
    intelligence: 0,
    strength: 0,
    speed: -10,
    durability: -5,
    power: 0,
    combat: -5,
  },
  {
    id: 9,
    name: 'Pepper in your nose',
    intelligence: -5,
    strength: 0,
    speed: 0,
    durability: -10,
    power: -5,
    combat: 0,
  },
  {
    id: 11,
    name: 'Lace-up corset',
    intelligence: 0,
    strength: -5,
    speed: -5,
    durability: -15,
    power: -5,
    combat: 0,
  },
  {
    id: 12,
    name: 'Display : float',
    intelligence: 0,
    strength: -15,
    speed: 0,
    durability: -5,
    power: 0,
    combat: -5,
  },
  {
    id: 13,
    name: 'Tartiflette',
    intelligence: 0,
    strength: -5,
    speed: -15,
    durability: -20,
    power: -5,
    combat: 0,
  },
  {
    id: 14,
    name: 'Nobody is nowhere',
    intelligence: -15,
    strength: 0,
    speed: -5,
    durability: 0,
    power: 0,
    combat: -10,
  },
  {
    id: 16,
    name: 'Internet Explorer',
    intelligence: -10,
    strength: -25,
    speed: 0,
    durability: -10,
    power: -10,
    combat: 0,
  },
  {
    id: 17,
    name: 'Banana peel',
    intelligence: 0,
    strength: -5,
    speed: -10,
    durability: 0,
    power: -10,
    combat: 0,
  },
];

const weapons = [
  {
    id: 0,
    name: 'No weapon',
    intelligence: 0,
    strength: 0,
    speed: 0,
    durability: 0,
    power: 0,
    combat: 0,
  },
  {
    id: 2,
    name: 'Excalibur',
    intelligence: 0,
    strength: 15,
    speed: 0,
    durability: 0,
    power: 10,
    combat: 10,
  },
  {
    id: 3,
    name: 'Invisibility cloak',
    intelligence: 5,
    strength: 0,
    speed: 15,
    durability: 5,
    power: 0,
    combat: 0,
  },
  {
    id: 5,
    name: 'Panoramix potion',
    intelligence: 0,
    strength: 25,
    speed: 15,
    durability: 0,
    power: 25,
    combat: 0,
  },
  {
    id: 6,
    name: 'Dynamite sticks',
    intelligence: 0,
    strength: 5,
    speed: 0,
    durability: 0,
    power: 20,
    combat: 10,
  },
  {
    id: 7,
    name: 'Leather Sling',
    intelligence: 0,
    strength: 5,
    speed: 5,
    durability: 0,
    power: 0,
    combat: 5,
  },
  {
    id: 8,
    name: 'Pink dotted mushroom',
    intelligence: 25,
    strength: 0,
    speed: 25,
    durability: 10,
    power: 0,
    combat: 25,
  },
  {
    id: 9,
    name: 'Blue shell',
    intelligence: 0,
    strength: 15,
    speed: 0,
    durability: 0,
    power: 10,
    combat: 0,
  },
  {
    id: 10,
    name: 'Toilet plunger',
    intelligence: 0,
    strength: 10,
    speed: 0,
    durability: 0,
    power: 5,
    combat: 0,
  },
  {
    id: 12,
    name: 'Tank',
    intelligence: 0,
    strength: 25,
    speed: 0,
    durability: 15,
    power: 15,
    combat: 0,
  },
  {
    id: 13,
    name: 'The Delorean',
    intelligence: 0,
    strength: 0,
    speed: 25,
    durability: 10,
    power: 0,
    combat: 0,
  },
  {
    id: 16,
    name: 'Screaming hotdog',
    intelligence: 0,
    strength: 10,
    speed: 0,
    durability: 0,
    power: 10,
    combat: 0,
  },
  {
    id: 17,
    name: 'Everybody is everywhere',
    intelligence: 15,
    strength: 0,
    speed: 5,
    durability: 0,
    power: 0,
    combat: 10,
  },
];

// ***Fields/Conditions***
const fields = [
  {
    id: 0,
    name: 'Nowhere',
    intelligence: '',
    strength: '',
    speed: '',
    durability: '',
    power: '',
    combat: '',
  },
  {
    id: 1,
    name: 'In an ice arena, approaching -15°C',
    intelligence: 10,
    strength: '',
    speed: 80,
    durability: '',
    power: '',
    combat: '',
  },
  {
    id: 2,
    name: 'In the crater of a prehistoric volcano',
    intelligence: '',
    strength: '',
    speed: '',
    durability: 10,
    power: '',
    combat: 90,
  },
  {
    id: 3,
    name: 'On the beach, during a hurricane',
    intelligence: 20,
    strength: '',
    speed: 80,
    durability: '',
    power: 70,
    combat: '',
  },
  {
    id: 4,
    name: 'In a sploch sploch swamp',
    intelligence: '',
    strength: '',
    speed: 20,
    durability: 30,
    power: '',
    combat: '',
  },
  {
    id: 5,
    name: 'In a trampoline full of kids',
    intelligence: '',
    strength: '',
    speed: 60,
    durability: 80,
    power: '',
    combat: 70,
  },
  {
    id: 6,
    name: 'In the Oceanus Borealis on Mars',
    intelligence: 100,
    strength: '',
    speed: '',
    durability: '',
    power: '',
    combat: 40,
  },
];

export { handicaps, weapons, fields };
