const handicaps = {
  HandsTied: {
    id: 2,
    name: 'Hands tied behind the back',
    intelligence: 0,
    strength: -10,
    speed: -20,
    durability: 0,
    power: 0,
    combat: 0,
  },
  Hangover: {
    id: 3,
    name: 'Hangover',
    intelligence: -15,
    strength: 0,
    speed: 0,
    durability: -10,
    power: 0,
    combat: 0,
  },
  LeadenShoes: {
    id: 4,
    name: 'Leaden shoes',
    intelligence: 0,
    strength: 0,
    speed: -25,
    durability: -10,
    power: 0,
    combat: 0,
  },
  SadSong: {
    id: 5,
    name: 'All by myself in your head',
    intelligence: 0,
    strength: -5,
    speed: -5,
    durability: -5,
    power: 0,
    combat: -10,
  },
  Jarjarbinks: {
    id: 6,
    name: 'Jar Jar Binks by your side',
    intelligence: 0,
    strength: 0,
    speed: -10,
    durability: -5,
    power: 0,
    combat: -5,
  },
  // Flu: {
  //   id: 7,
  //   name: 'Flu',
  //   intelligence: 0,
  //   strength: -15,
  //   speed: -10,
  //   durability: -5,
  //   power: 0,
  //   combat: 0,
  // },
  // Weightlessness: {
  //   id: 8,
  //   name: 'Weightlessness',
  //   intelligence: 0,
  //   strength: -25,
  //   speed: 0,
  //   durability: 0,
  //   power: -10,
  //   combat: 0,
  // },
  Pepper: {
    id: 9,
    name: 'Pepper in your nose',
    intelligence: -5,
    strength: 0,
    speed: 0,
    durability: -10,
    power: -5,
    combat: 0,
  },
  // Blindfolden: {
  //   id: 10,
  //   name: 'Blindfolden',
  //   intelligence: 0,
  //   strength: 0,
  //   speed: -15,
  //   durability: 0,
  //   power: -10,
  //   combat: 0,
  // },
  Corset: {
    id: 11,
    name: 'Lace-up corset',
    intelligence: 0,
    strength: -5,
    speed: -5,
    durability: -15,
    power: -5,
    combat: 0,
  },
  Float: {
    id: 12,
    name: 'Display : float',
    intelligence: 0,
    strength: -15,
    speed: 0,
    durability: -5,
    power: 0,
    combat: -5,
  },
  Tartiflette: {
    id: 13,
    name: 'Tartiflette',
    intelligence: 0,
    strength: -5,
    speed: -15,
    durability: -20,
    power: -5,
    combat: 0,
  },
  Nobody: {
    id: 14,
    name: 'Nobody is nowhere',
    intelligence: -15,
    strength: 0,
    speed: -5,
    durability: 0,
    power: 0,
    combat: -10,
  },
  // Agoraphobia: {
  //   id: 15,
  //   name: 'Agoraphobia',
  //   intelligence: 0,
  //   strength: -5,
  //   speed: -15,
  //   durability: 0,
  //   power: -5,
  //   combat: -10,
  // },
  InternetExplorer: {
    id: 16,
    name: 'Internet Explorer',
    intelligence: -10,
    strength: -25,
    speed: 0,
    durability: -10,
    power: -10,
    combat: 0,
  },
  Banana: {
    id: 17,
    name: 'Banana peel',
    intelligence: 0,
    strength: -5,
    speed: -10,
    durability: 0,
    power: -10,
    combat: 0,
  },
};
const weapons = {
  Excalibur: {
    id: 2,
    name: 'Excalibur',
    intelligence: 0,
    strength: 15,
    speed: 0,
    durability: 0,
    power: 10,
    combat: 10,
  },
  Cloak: {
    id: 3,
    name: 'Invisibility cloak',
    intelligence: 5,
    strength: 0,
    speed: 15,
    durability: 5,
    power: 0,
    combat: 0,
  },
  // RedPill: {
  //   id: 4,
  //   name: 'The red pill',
  //   intelligence: 25,
  //   strength: 0,
  //   speed: 0,
  //   durability: 0,
  //   power: 0,
  //   combat: 10,
  // },
  Potion: {
    id: 5,
    name: 'Panoramix potion',
    intelligence: 0,
    strength: 25,
    speed: 15,
    durability: 0,
    power: 25,
    combat: 0,
  },
  Dynamite: {
    id: 6,
    name: 'Dynamite sticks',
    intelligence: 0,
    strength: 5,
    speed: 0,
    durability: 0,
    power: 20,
    combat: 10,
  },
  Sling: {
    id: 7,
    name: 'Leather Sling',
    intelligence: 0,
    strength: 5,
    speed: 5,
    durability: 0,
    power: 0,
    combat: 5,
  },
  Mushroom: {
    id: 8,
    name: 'Pink dotted mushroom',
    intelligence: 25,
    strength: 0,
    speed: 25,
    durability: 10,
    power: 0,
    combat: 25,
  },
  BlueShell: {
    id: 9,
    name: 'Blue shell',
    intelligence: 0,
    strength: 15,
    speed: 0,
    durability: 0,
    power: 10,
    combat: 0,
  },
  Plunger: {
    id: 10,
    name: 'Toilet plunger',
    intelligence: 0,
    strength: 10,
    speed: 0,
    durability: 0,
    power: 5,
    combat: 0,
  },
  // VoodooDoll: {
  //   id: 11,
  //   name: 'Voodoo doll',
  //   intelligence: 5,
  //   strength: 10,
  //   speed: 5,
  //   durability: 0,
  //   power: 10,
  //   combat: 0,
  // },
  Tank: {
    id: 12,
    name: 'Tank',
    intelligence: 0,
    strength: 25,
    speed: 0,
    durability: 15,
    power: 15,
    combat: 0,
  },
  Delorean: {
    id: 13,
    name: 'The Delorean',
    intelligence: 0,
    strength: 0,
    speed: 25,
    durability: 10,
    power: 0,
    combat: 0,
  },
  // Aegis: {
  //   id: 14,
  //   name: 'Aegis',
  //   intelligence: 0,
  //   strength: 0,
  //   speed: 0,
  //   durability: 25,
  //   power: 0,
  //   combat: 5,
  // },
  // Tornado: {
  //   id: 15,
  //   name: 'Tornado',
  //   intelligence: 0,
  //   strength: 0,
  //   speed: 25,
  //   durability: 20,
  //   power: 0,
  //   combat: 10,
  // },
  Hotdog: {
    id: 16,
    name: 'Screaming hotdog',
    intelligence: 0,
    strength: 10,
    speed: 0,
    durability: 0,
    power: 10,
    combat: 0,
  },
  Everybody: {
    id: 17,
    name: 'Everybody is everywhere',
    intelligence: 15,
    strength: 0,
    speed: 5,
    durability: 0,
    power: 0,
    combat: 10,
  },
};

// ***Fields/Conditions***
const fields = {
  IceArena: {
    name: 'In an ice arena, in -15°C',
    intelligence: 10,
    strength: '',
    speed: 80,
    durability: '',
    power: '',
    combat: '',
  },
  Volcano: {
    name: 'In the crater of a prehistoric volcano',
    intelligence: '',
    strength: '',
    speed: '',
    durability: '',
    power: '',
    combat: '',
  },
  Beach: {
    name: 'On the beach, during a hurricane',
    intelligence: '',
    strength: '',
    speed: '',
    durability: '',
    power: '',
    combat: '',
  },
  Swamp: {
    name: 'In a sploch sploch swamp',
    intelligence: '',
    strength: '',
    speed: '',
    durability: '',
    power: '',
    combat: '',
  },
  Trampoline: {
    name: 'In a trampoline full of kids',
    intelligence: '',
    strength: '',
    speed: '',
    durability: '',
    power: '',
    combat: '',
  },
  Mars: {
    name: 'In the middle of the Oceanus Borealis on Mars',
    intelligence: '',
    strength: '',
    speed: '',
    durability: '',
    power: '',
    combat: '',
  },
};

export { handicaps, weapons, fields };
